services:
  web:
    build: .
    container_name: django_erp_web
    restart: unless-stopped
    tty: true
    stdin_open: true
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      DJANGO_SECRET_KEY: "change-this-secret-key"
      DJANGO_DEBUG: "True"
      DB_NAME: "django_erp"
      DB_USER: "erp_user"
      DB_PASSWORD: "erp_password"
      DB_HOST: "db"
      DB_PORT: "3306"
    depends_on:
      - db

  db:
    image: mysql:8.4
    container_name: django_erp_mysql
    restart: always
    environment:
      MYSQL_DATABASE: "django_erp"
      MYSQL_USER: "erp_user"
      MYSQL_PASSWORD: "erp_password"
      MYSQL_ROOT_PASSWORD: "root_password"
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  adminer:
    image: adminer:latest
    container_name: django_erp_adminer
    restart: always
    ports:
      - "8081:8081"
    depends_on:
      - db

volumes:
  mysql_data:
